# Generated by Django 6.0.2 on 2026-02-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название встречи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время')),
                ('max_participants', models.PositiveIntegerField(verbose_name='Максимальное количество мест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='books.book', verbose_name='Обсуждаемая книга')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['-event_date'],
            },
        ),
    ]
