# Generated by Django 6.0.2 on 2026-02-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_status', models.CharField(choices=[('want', 'Хочу прочитать'), ('reading', 'Читаю'), ('read', 'Прочитал(a)')], max_length=10, verbose_name='Статус чтения')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Статус книги пользователя',
                'verbose_name_plural': 'Статусы книг пользователей',
            },
        ),
    ]
