# Generated by Django 6.0.2 on 2026-02-26 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='userbook',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статус книги пользователя', 'verbose_name_plural': 'Статусы книг пользователей'},
        ),
        migrations.AddField(
            model_name='userbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления в список'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbook',
            name='finished_reading_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание чтения'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='started_reading_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало чтения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='books.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='reading_status',
            field=models.CharField(choices=[('want', 'Хочу прочитать'), ('reading', 'Читаю'), ('read', 'Прочитал(a)')], default='want', max_length=15, verbose_name='Статус чтения'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='books_book_author_b941fe_idx'),
        ),
    ]
